 [api]
google_maps = "AIzaSyAFSAv-zL39UHSVoFTImThIUgX8bv2zA-4"

[auth]
# Senha para acesso geral ao aplicativo (jรก existe)
senha = "csc2025"

# NOVA SENHA para acessar a aba Editor de Dados
editor_senha = "admti"






